export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_FAILURE = 'FETCH_MEMBERS_FAILURE';

export const FETCH_MEMBER_REQUEST = 'FETCH_MEMBER_REQUEST';
export const FETCH_MEMBER_SUCCESS = 'FETCH_MEMBER_SUCCESS';
export const FETCH_MEMBER_FAILURE = 'FETCH_MEMBER_FAILURE';

export const DESTROY_MEMBER_REQUEST = 'DESTROY_MEMBER_REQUEST';
export const DESTROY_MEMBER_SUCCESS = 'DESTROY_MEMBER_SUCCESS';
export const DESTROY_MEMBER_FAILURE = 'DESTROY_MEMBER_FAILURE';

export const CREATE_ORGANIZER_REQUEST = 'CREATE_ORGANIZER_REQUEST';
export const CREATE_ORGANIZER_SUCCESS = 'CREATE_ORGANIZER_SUCCESS';
export const CREATE_ORGANIZER_FAILURE = 'CREATE_ORGANIZER_FAILURE';

export const REMOVE_ORGANIZER_REQUEST = 'REMOVE_ORGANIZER_REQUEST';
export const REMOVE_ORGANIZER_SUCCESS = 'REMOVE_ORGANIZER_SUCCESS';
export const REMOVE_ORGANIZER_FAILURE = 'REMOVE_ORGANIZER_FAILURE';
