export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';

export const DESTROY_EVENT_REQUEST = 'DESTROY_EVENT_REQUEST';
export const DESTROY_EVENT_SUCCESS = 'DESTROY_EVENT_SUCCESS';
export const DESTROY_EVENT_FAILURE = 'DESTROY_EVENT_FAILURE';

export const ADD_ATTENDEE_REQUEST = 'ADD_ATTENDEE_REQUEST';
export const ADD_ATTENDEE_SUCCESS = 'ADD_ATTENDEE_SUCCESS';
export const ADD_ATTENDEE_FAILURE = 'ADD_ATTENDEE_FAILURE';

export const REMOVE_ATTENDEE_REQUEST = 'REMOVE_ATTENDEE_REQUEST';
export const REMOVE_ATTENDEE_SUCCESS = 'REMOVE_ATTENDEE_SUCCESS';
export const REMOVE_ATTENDEE_FAILURE = 'REMOVE_ATTENDEE_FAILURE';

export const SCHEDULE_SURVEY_REQUEST = 'SCHEDULE_SURVEY_REQUEST';
export const SCHEDULE_SURVEY_SUCCESS = 'SCHEDULE_SURVEY_SUCCESS';
export const SCHEDULE_SURVEY_FAILURE = 'SCHEDULE_SURVEY_FAILURE';
